services:
  drones_as2_unizar:
    image: drones_as2_unizar
    build:
      context: ./docker/
      dockerfile: Dockerfile
    container_name: drones_as2_unizar
    environment:
      DISPLAY: $DISPLAY
      ROS_DOMAIN_ID: 3
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    privileged: true
    volumes:
      # X11
      - ~/.Xauthority:/root/.Xauthority
      # 
      - /dev/:/dev
      # By default, mount the current directory. Change to the line below for development
      - ./drones_as2_unizar:/root/drones_unizar_ws/src/drones_as2_unizar
      # - ./drones_unizar_dev_ws:/root/drones_unizar_dev_ws
  
    network_mode: "host"
    command: tail -f /dev/null
